version: "3.6"

services:
  rabbitmq:
    image: masstransit/rabbitmq:latest
    ports:
     - "5672:5672"
     - "15672:15672"
     - "15692:15692"
  sqlserver:
    image: masstransit/sqlserver-quartz:latest
    user: root # required for volume mapping to work
    ports:
      - 1433:1433
    volumes:
     - mssql-server-linux-data:/var/opt/mssql/data


volumes:
  mssql-server-linux-data:
